name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -name: initialize node
        npm init
        
      -name: install npm 
        npm install
     

      - name : install gh-pages
        npm install gh-pages --save-dev

      - name: Checkout repository
        uses: actions/checkout@v2

      

      - name: Deploy to GitHub Pages
        uses: katlehomyezaBBD/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          target_branch: gh-pages  # Target branch for GitHub Pages

